version: 2.1
orbs:
  kitchen: sous-chefs/kitchen@2.1.1
workflows:
  version: 2
  test:
    jobs:
      - kitchen/dokken-single:
          suite: default
      - kitchen/dokken-single:
          suite: cleanup
      - kitchen/dokken-single:
          suite: uidgid
      - kitchen/dokken-single:
          suite: notification
  nightly:
    triggers:
      - schedule:
          cron: "0 15 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - kitchen/dokken-single:
          suite: default
      - kitchen/dokken-single:
          suite: cleanup
      - kitchen/dokken-single:
          suite: uidgid
      - kitchen/dokken-single:
          suite: notification
